# Generated by Django 4.0 on 2022-08-24 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('12', '12'), ('16', '16'), ('32', '32')], max_length=2, verbose_name='ядер шт')),
                ('ram', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('12', '12'), ('16', '16'), ('32', '32')], max_length=2, verbose_name='озу Гб')),
                ('hdd', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('12', '12'), ('16', '16'), ('32', '32')], max_length=2, verbose_name='hdd Тб')),
                ('status', models.CharField(choices=[('started', 'started'), ('blocked', 'blocked'), ('stopped', 'stopped')], max_length=7, verbose_name='статус сервера')),
            ],
        ),
    ]
