# Generated by Django 4.0 on 2022-08-24 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_p', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='ядро шт')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdd_p', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='hdd тб')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_p', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='озу гб')),
            ],
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'started'), ('blocked', 'blocked'), ('stopped', 'stopped')], max_length=7, verbose_name='статус сервера')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.cpu')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.hdd')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.ram')),
            ],
        ),
    ]
