# Generated by Django 4.0 on 2022-08-26 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps_v3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPU'},
        ),
        migrations.AlterModelOptions(
            name='hdd',
            options={'verbose_name': 'HDD', 'verbose_name_plural': 'HDD'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM', 'verbose_name_plural': 'RAM'},
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_p',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(64)], verbose_name='ядро шт'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='hdd_p',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(16)], verbose_name='hdd тб'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_p',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(512)], verbose_name='озу гб'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.cpu', to_field='cpu_p'),
        ),
    ]
