# Generated by Django 4.0 on 2022-08-26 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps_v3', '0002_alter_cpu_options_alter_hdd_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='hdd_p',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='hdd тб'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_p',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(512)], verbose_name='озу гб'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='hdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.hdd', to_field='hdd_p'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps_v3.ram', to_field='ram_p'),
        ),
    ]
